name: Deploy into production server

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy at remote server
        uses: appleboy/ssh-action@master
        with:
          host:     ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key:      ${{ secrets.SERVER_SSHKEY }}
          port:     ${{ secrets.SERVER_PORT }}
          envs: DIR
          script_stop: true
          script: |
            cd $DIR
            git pull origin master -f
            composer install
            php artisan migrate
        env:
          DIR: ~/public_html/api.afes.info
